sudo: false

language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - lerna run -- prune
  - npm install -g coveralls

install:
  - lerna bootstrap

script:
  - lerna run -- test

after_success:
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true
